#!/bin/zsh

echo "clearing out live packs"
rm -rf live

echo "creating new live pack dir"
mkdir live

echo "copying content from dev packs"
cp -pRL dev/* live/

echo "removing dev detritus"
rm -rf live/**/vendor
rm -rf live/**/.git*
rm -rf live/**/*.elc
